services:
  hub:
    image: selenium/hub:4.25
  chrome:
    image: selenium/node-chrome:4.25
    shm_size: '1g'
    depends_on:
      - hub
    deploy:
      replicas: 0
    env_file: .env
  firefox:
    image: selenium/node-firefox:4.25
    shm_size: '1g'
    depends_on:
      - hub
    deploy:
      replicas: 0
    env_file: .env
