services:
  test-suite:
    image: tempori/selenium
    environment:
      - BROWSER
      - HUB_HOST=hub
      - THREAD_COUNT=3
      - TEST_SUITE
    volumes:
      - ./output/test-suite:/home/selenium-docker/test-output
